### ISSUE TITLE
如何检测滚动到了第几条？有对外接口吗？

### ISSUE THREAD

**Issue by xinqidian** [ColeXm/CCAdsPlayView#3]

**Comment by ColeXm** [comment]
目前只有点击才能获取，而且我想知道什么情况下需要检测呢。

**Comment by xinqidian** [comment]
对不起 一直没有看 例如我想自己弄一个 1/4  这样的标志   翻到第几页的标记   人生总能遇到几个独特客户

**Comment by ColeXm** [comment]
可以的，你把 pageControl的index开出来当成属性就可以了。

**Comment by xinqidian** [comment]
这样也是一个解决方案  就是缺少监听  需要自己弄一个  NSNotificationCenter
